"""empty message

Revision ID: 3c8f0856b635
Revises: a7b5e34eac58
Create Date: 2018-02-24 13:05:25.721719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8f0856b635'
down_revision = 'a7b5e34eac58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('API',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=24), nullable=True),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.Column('param', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('API')
    # ### end Alembic commands ###
