"""empty message

Revision ID: 555b0172dcf4
Revises: 7205a10c6adb
Create Date: 2018-02-23 10:24:50.925210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555b0172dcf4'
down_revision = '7205a10c6adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('desc', sa.String(length=125), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'desc')
    # ### end Alembic commands ###
