"""empty message

Revision ID: 7205a10c6adb
Revises: c335112c60b1
Create Date: 2018-02-22 19:02:05.900052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7205a10c6adb'
down_revision = 'c335112c60b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('blue', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nav')
    # ### end Alembic commands ###
