"""empty message

Revision ID: 78db240ccd59
Revises: 3c8f0856b635
Create Date: 2018-02-25 16:28:13.432332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78db240ccd59'
down_revision = '3c8f0856b635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_log', sa.Column('is_recommend', sa.Boolean(), nullable=True))
    op.add_column('tv_log', sa.Column('time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_log', 'time')
    op.drop_column('tv_log', 'is_recommend')
    # ### end Alembic commands ###
