"""empty message

Revision ID: 9acfc3afbba9
Revises: 555b0172dcf4
Create Date: 2018-02-23 22:11:06.469727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acfc3afbba9'
down_revision = '555b0172dcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=255), nullable=True),
    sa.Column('tv_name', sa.String(length=255), nullable=True),
    sa.Column('time', sa.String(length=255), nullable=True),
    sa.Column('day', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_name')
    )
    op.add_column('user', sa.Column('device', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('info', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'info')
    op.drop_column('user', 'device')
    op.drop_table('tv_program')
    op.drop_table('tv_log')
    op.drop_table('TV')
    # ### end Alembic commands ###
